// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7QgE_WycWZPJbkVLzxhMP_nStwDrNLQI',
    appId: '1:257618089832:web:e2585262bcf4245c9ea8dd',
    messagingSenderId: '257618089832',
    projectId: 'e-kosan-mobile',
    authDomain: 'e-kosan-mobile.firebaseapp.com',
    storageBucket: 'e-kosan-mobile.firebasestorage.app',
    measurementId: 'G-VD6P1YM33L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTmNlA5MVprxd1N22kJelLMWMKC2WLfY',
    appId: '1:257618089832:android:1258e8464c46ac609ea8dd',
    messagingSenderId: '257618089832',
    projectId: 'e-kosan-mobile',
    storageBucket: 'e-kosan-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_05eL3IcmB6Lx2p3PQMCPkjoL4kk49A',
    appId: '1:257618089832:ios:c1ba34838b6cce1b9ea8dd',
    messagingSenderId: '257618089832',
    projectId: 'e-kosan-mobile',
    storageBucket: 'e-kosan-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eKosan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_05eL3IcmB6Lx2p3PQMCPkjoL4kk49A',
    appId: '1:257618089832:ios:c1ba34838b6cce1b9ea8dd',
    messagingSenderId: '257618089832',
    projectId: 'e-kosan-mobile',
    storageBucket: 'e-kosan-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eKosan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7QgE_WycWZPJbkVLzxhMP_nStwDrNLQI',
    appId: '1:257618089832:web:3db631360cf14e049ea8dd',
    messagingSenderId: '257618089832',
    projectId: 'e-kosan-mobile',
    authDomain: 'e-kosan-mobile.firebaseapp.com',
    storageBucket: 'e-kosan-mobile.firebasestorage.app',
    measurementId: 'G-YJCPBVE99H',
  );
}
